/**
 * Strings - interface text for Case Changer in every supported language (1.4).
 *
 * English is the master list. Every other language may leave a key out, in
 * which case the English text is used. {placeholders} are filled in by
 * Strings.format(). The style names show the style they describe, so they
 * keep their own capitalisation in every language.
 *
 * Menu names (Extensions, Sambungan, Erweiterungen...) and the word for
 * "add-on" follow Google's own help pages in each language
 * (support.google.com/docs/answer/2942256?hl=xx), checked 21 September 2026.
 * Filipino has no localised help page, so Tagalog keeps "Extensions".
 * Product names follow the same pages: Hojas de cálculo, Tabellen, Planilhas,
 * Fogli, Spreadsheets, E-Tablolar, Υπολογιστικά φύλλα, Spreadsheet. French,
 * Malay and Tagalog use the English names, as Google does there.
 */
var Strings = (function () {
  'use strict';

  var T = {};

  T.en = {
    heading: 'Change selected text to',
    hint: 'Highlight some text (or select cells in Sheets, or a text box in Slides), then click a style. Bold, links and colours are kept.',
    cycle: 'Cycle case', cycleTip: 'UPPERCASE, then lowercase, then Title Case',
    preview: 'Preview', previewTip: 'Show how the selected text would look in each style',
    favLabel: 'Your most used', allLabel: 'All styles',
    style_upper: 'UPPERCASE', style_lower: 'lowercase', style_sentence: 'Sentence case', style_title: 'Title Case',
    style_capitalize: 'Capitalize Each Word', style_inverse: 'iNVERSE cASE', style_alternating: 'aLtErNaTiNg cAsE',
    style_snake: 'snake_case', style_kebab: 'kebab-case',
    working: 'Working...', workingWhole: 'Working on the whole file...', reading: 'Reading the selection...',
    nothingPreview: 'Nothing to preview. Select some text first.',
    previewDone: 'Preview of the first line. Click a style to apply it.',
    wentWrong: 'Something went wrong: {error}',
    whole_docs: 'Change the entire document', whole_sheets: 'Change the entire sheet', whole_slides: 'Change the entire presentation',
    settings: 'Settings',
    keepAcronyms: 'Keep acronyms as they are (NASA, KL, UMNO) in Sentence case and Title Case',
    languageLabel: 'Text language: sets the small words Title Case keeps lowercase (of, the, dan, de, der...) and the English capital I',
    langAuto: 'Auto: from the text, else {language}',
    extraLabel: 'Also keep these words lowercase (separate with spaces)', extraPlaceholder: 'e.g. vs feat',
    protectedLabel: 'Never change these words (spelling kept in every style)', protectedPlaceholder: 'e.g. iPhone eBay macOS',
    properNouns: 'Sentence case capitalises days, months, languages and places (Monday, Kuala Lumpur)',
    skipHeader: 'In Sheets, leave the header row alone when a whole column is selected',
    darkSidebar: 'Dark sidebar',
    uiLanguageLabel: 'Sidebar language', uiAuto: 'Auto: {language} (your account language)',
    uiReload: 'Reopen the sidebar to see it. The menu follows your Google account language.',
    saved: 'Saved', couldNotSave: 'Could not save: {error}',
    tip: 'Tip: the same styles are in the Extensions > Case Changer menu, so you can close this sidebar if you prefer.',
    rateAsk: 'Finding it useful? A short review on the Marketplace helps others find it.', rateYes: 'Rate it', rateNo: 'Not now',
    menu_cycle: 'Cycle case (UPPER > lower > Title)', menu_repeat: 'Repeat last style', menu_sidebar: 'Open sidebar', menu_help: 'How it works',
    msg_changed: 'Changed to {style}.', msg_nothingToChange: 'Nothing to change.', msg_nothingSelected: 'Nothing is selected.',
    msg_headerSkipped: 'Header row skipped.', msg_headersSkipped: '{n} header rows skipped.',
    msg_unknownStyle: 'Unknown case style.', msg_wrongHost: 'Open this add-on from Google Docs, Sheets or Slides.',
    msg_noLast: 'No style has been used yet. Pick one from the menu first.',
    ask_docs: 'Nothing is selected. Change the entire document instead?',
    ask_sheets: 'Nothing is selected. Change the entire sheet instead?',
    ask_slides: 'Nothing is selected. Change the entire presentation instead?',
    help: 'Select some text (in Sheets: select cells; in Slides: highlight text or select a text box), then pick a case style from the Case Changer menu or the sidebar.\n\nCycle case switches between UPPERCASE, lowercase and Title Case. Repeat last style does what it says.\nWith nothing selected you can change the whole file.\n\nFormatting such as bold, links and colours is kept.\nNothing leaves your file: the add-on only reads the text you select and writes it back in the new case.'
  };

  T.ms = {
    heading: 'Tukar teks yang dipilih kepada',
    hint: 'Serlahkan teks (atau pilih sel dalam Sheets, atau kotak teks dalam Slides), kemudian klik satu gaya. Huruf tebal, pautan dan warna dikekalkan.',
    cycle: 'Kitar huruf', cycleTip: 'HURUF BESAR, kemudian huruf kecil, kemudian Huruf Tajuk',
    preview: 'Pratonton', previewTip: 'Tunjukkan rupa teks yang dipilih dalam setiap gaya',
    favLabel: 'Paling kerap anda guna', allLabel: 'Semua gaya',
    style_upper: 'HURUF BESAR', style_lower: 'huruf kecil', style_sentence: 'Huruf ayat', style_title: 'Huruf Tajuk',
    style_capitalize: 'Huruf Besar Setiap Perkataan', style_inverse: 'hURUF sONGSANG', style_alternating: 'hUrUf BeRsElAnG',
    working: 'Sedang diproses...', workingWhole: 'Sedang memproses seluruh fail...', reading: 'Membaca pilihan...',
    nothingPreview: 'Tiada apa untuk dipratonton. Pilih teks dahulu.',
    previewDone: 'Pratonton baris pertama. Klik satu gaya untuk menggunakannya.',
    wentWrong: 'Ada masalah: {error}',
    whole_docs: 'Tukar seluruh dokumen', whole_sheets: 'Tukar seluruh helaian', whole_slides: 'Tukar seluruh persembahan',
    settings: 'Tetapan',
    keepAcronyms: 'Kekalkan akronim (NASA, KL, UMNO) dalam Huruf ayat dan Huruf Tajuk',
    languageLabel: 'Bahasa teks: menentukan kata kecil yang kekal huruf kecil dalam Huruf Tajuk (dan, di, ke, of, the...) dan huruf besar I bahasa Inggeris',
    langAuto: 'Auto: daripada teks, jika tidak {language}',
    extraLabel: 'Kekalkan juga perkataan ini dalam huruf kecil (asingkan dengan ruang)', extraPlaceholder: 'cth. vs feat',
    protectedLabel: 'Jangan ubah perkataan ini (ejaan dikekalkan dalam setiap gaya)', protectedPlaceholder: 'cth. iPhone eBay macOS',
    properNouns: 'Huruf ayat membesarkan huruf pertama hari, bulan, bahasa dan tempat (Isnin, Kuala Lumpur)',
    skipHeader: 'Dalam Sheets, biarkan baris tajuk apabila seluruh lajur dipilih',
    darkSidebar: 'Bar sisi gelap',
    uiLanguageLabel: 'Bahasa bar sisi', uiAuto: 'Auto: {language} (bahasa akaun anda)',
    uiReload: 'Buka semula bar sisi untuk melihatnya. Menu mengikut bahasa akaun Google anda.',
    saved: 'Disimpan', couldNotSave: 'Tidak dapat disimpan: {error}',
    tip: 'Petua: gaya yang sama ada dalam menu Sambungan > Case Changer, jadi bar sisi ini boleh ditutup jika anda mahu.',
    rateAsk: 'Berguna? Ulasan ringkas di Marketplace membantu orang lain menemuinya.', rateYes: 'Beri ulasan', rateNo: 'Bukan sekarang',
    menu_cycle: 'Kitar huruf (BESAR > kecil > Tajuk)', menu_repeat: 'Ulang gaya terakhir', menu_sidebar: 'Buka bar sisi', menu_help: 'Cara guna',
    msg_changed: 'Ditukar kepada {style}.', msg_nothingToChange: 'Tiada apa untuk ditukar.', msg_nothingSelected: 'Tiada apa yang dipilih.',
    msg_headerSkipped: 'Baris tajuk dilangkau.', msg_headersSkipped: '{n} baris tajuk dilangkau.',
    msg_unknownStyle: 'Gaya huruf tidak dikenali.', msg_wrongHost: 'Buka alat tambah ini daripada Google Docs, Sheets atau Slides.',
    msg_noLast: 'Belum ada gaya yang digunakan. Pilih satu daripada menu dahulu.',
    ask_docs: 'Tiada apa yang dipilih. Tukar seluruh dokumen?',
    ask_sheets: 'Tiada apa yang dipilih. Tukar seluruh helaian?',
    ask_slides: 'Tiada apa yang dipilih. Tukar seluruh persembahan?',
    help: 'Pilih teks (dalam Sheets: pilih sel; dalam Slides: serlahkan teks atau pilih kotak teks), kemudian pilih gaya huruf daripada menu Case Changer atau bar sisi.\n\nKitar huruf bertukar antara HURUF BESAR, huruf kecil dan Huruf Tajuk. Ulang gaya terakhir mengulang gaya yang terakhir digunakan.\nJika tiada apa dipilih, anda boleh menukar seluruh fail.\n\nFormat seperti huruf tebal, pautan dan warna dikekalkan.\nTiada apa yang keluar daripada fail anda: alat tambah ini hanya membaca teks yang dipilih dan menulisnya semula dalam gaya baharu.'
  };

  T.id = {
    heading: 'Ubah teks yang dipilih menjadi',
    hint: 'Sorot teks (atau pilih sel di Spreadsheet, atau kotak teks di Slide), lalu klik sebuah gaya. Huruf tebal, tautan, dan warna tetap dipertahankan.',
    cycle: 'Putar huruf', cycleTip: 'HURUF BESAR, lalu huruf kecil, lalu Huruf Judul',
    preview: 'Pratinjau', previewTip: 'Tampilkan tampilan teks yang dipilih dalam setiap gaya',
    favLabel: 'Paling sering Anda pakai', allLabel: 'Semua gaya',
    style_upper: 'HURUF BESAR', style_lower: 'huruf kecil', style_sentence: 'Huruf kalimat', style_title: 'Huruf Judul',
    style_capitalize: 'Huruf Besar Tiap Awal Kata', style_inverse: 'hURUF tERBALIK', style_alternating: 'hUrUf SeLaNg-SeLiNg',
    working: 'Sedang diproses...', workingWhole: 'Memproses seluruh file...', reading: 'Membaca pilihan...',
    nothingPreview: 'Tidak ada yang bisa dipratinjau. Pilih teks terlebih dahulu.',
    previewDone: 'Pratinjau baris pertama. Klik sebuah gaya untuk menerapkannya.',
    wentWrong: 'Terjadi kesalahan: {error}',
    whole_docs: 'Ubah seluruh dokumen', whole_sheets: 'Ubah seluruh sheet', whole_slides: 'Ubah seluruh presentasi',
    settings: 'Setelan',
    keepAcronyms: 'Pertahankan akronim (NASA, DKI, BUMN) pada Huruf kalimat dan Huruf Judul',
    languageLabel: 'Bahasa teks: menentukan kata kecil yang tetap huruf kecil pada Huruf Judul (dan, di, ke, of, the...) dan huruf besar I bahasa Inggris',
    langAuto: 'Otomatis: dari teks, jika tidak {language}',
    extraLabel: 'Pertahankan juga kata-kata ini dalam huruf kecil (pisahkan dengan spasi)', extraPlaceholder: 'mis. vs feat',
    protectedLabel: 'Jangan ubah kata-kata ini (ejaan dipertahankan di setiap gaya)', protectedPlaceholder: 'mis. iPhone eBay macOS',
    properNouns: 'Huruf kalimat mengapitalkan hari, bulan, bahasa, dan tempat (Senin, Jakarta)',
    skipHeader: 'Di Spreadsheet, biarkan baris judul saat seluruh kolom dipilih',
    darkSidebar: 'Sidebar gelap',
    uiLanguageLabel: 'Bahasa sidebar', uiAuto: 'Otomatis: {language} (bahasa akun Anda)',
    uiReload: 'Buka kembali sidebar untuk melihatnya. Menu mengikuti bahasa akun Google Anda.',
    saved: 'Tersimpan', couldNotSave: 'Tidak dapat menyimpan: {error}',
    tip: 'Tips: gaya yang sama ada di menu Ekstensi > Case Changer, jadi sidebar ini boleh ditutup.',
    rateAsk: 'Bermanfaat? Ulasan singkat di Marketplace membantu orang lain menemukannya.', rateYes: 'Beri ulasan', rateNo: 'Nanti saja',
    menu_cycle: 'Putar huruf (BESAR > kecil > Judul)', menu_repeat: 'Ulangi gaya terakhir', menu_sidebar: 'Buka sidebar', menu_help: 'Cara pakai',
    msg_changed: 'Diubah menjadi {style}.', msg_nothingToChange: 'Tidak ada yang perlu diubah.', msg_nothingSelected: 'Tidak ada yang dipilih.',
    msg_headerSkipped: 'Baris judul dilewati.', msg_headersSkipped: '{n} baris judul dilewati.',
    msg_unknownStyle: 'Gaya huruf tidak dikenal.', msg_wrongHost: 'Buka add-on ini dari Google Dokumen, Spreadsheet, atau Slide.',
    msg_noLast: 'Belum ada gaya yang digunakan. Pilih satu dari menu terlebih dahulu.',
    ask_docs: 'Tidak ada yang dipilih. Ubah seluruh dokumen?',
    ask_sheets: 'Tidak ada yang dipilih. Ubah seluruh sheet?',
    ask_slides: 'Tidak ada yang dipilih. Ubah seluruh presentasi?',
    help: 'Pilih teks (di Spreadsheet: pilih sel; di Slide: sorot teks atau pilih kotak teks), lalu pilih gaya huruf dari menu Case Changer atau sidebar.\n\nPutar huruf berganti antara HURUF BESAR, huruf kecil, dan Huruf Judul. Ulangi gaya terakhir mengulang gaya yang terakhir dipakai.\nJika tidak ada yang dipilih, Anda dapat mengubah seluruh file.\n\nFormat seperti huruf tebal, tautan, dan warna dipertahankan.\nTidak ada yang keluar dari file Anda: add-on ini hanya membaca teks yang dipilih dan menulisnya kembali dengan gaya baru.'
  };

  T.es = {
    heading: 'Cambiar el texto seleccionado a',
    hint: 'Selecciona texto (o celdas en Hojas de cálculo, o un cuadro de texto en Presentaciones) y haz clic en un estilo. La negrita, los enlaces y los colores se conservan.',
    cycle: 'Alternar', cycleTip: 'MAYÚSCULAS, luego minúsculas, luego Tipo Título',
    preview: 'Vista previa', previewTip: 'Muestra cómo quedaría el texto seleccionado en cada estilo',
    favLabel: 'Los que más usas', allLabel: 'Todos los estilos',
    style_upper: 'MAYÚSCULAS', style_lower: 'minúsculas', style_sentence: 'Tipo oración', style_title: 'Tipo Título',
    style_capitalize: 'Mayúscula En Cada Palabra', style_inverse: 'iNVERTIR mAYÚSCULAS', style_alternating: 'aLtErNaR mAyÚsCuLaS',
    working: 'Trabajando...', workingWhole: 'Procesando todo el archivo...', reading: 'Leyendo la selección...',
    nothingPreview: 'No hay nada que previsualizar. Selecciona texto primero.',
    previewDone: 'Vista previa de la primera línea. Haz clic en un estilo para aplicarlo.',
    wentWrong: 'Algo salió mal: {error}',
    whole_docs: 'Cambiar todo el documento', whole_sheets: 'Cambiar toda la hoja', whole_slides: 'Cambiar toda la presentación',
    settings: 'Ajustes',
    keepAcronyms: 'Mantener las siglas (NASA, ONU, UE) en Tipo oración y Tipo Título',
    languageLabel: 'Idioma del texto: define las palabras cortas que Tipo Título deja en minúscula (de, la, y, of, the...) y la I mayúscula del inglés',
    langAuto: 'Automático: según el texto, si no {language}',
    extraLabel: 'Mantener también estas palabras en minúscula (separadas por espacios)', extraPlaceholder: 'p. ej. vs feat',
    protectedLabel: 'No cambiar nunca estas palabras (se conserva su escritura en todos los estilos)', protectedPlaceholder: 'p. ej. iPhone eBay macOS',
    properNouns: 'Tipo oración pone en mayúscula países y ciudades (España, Madrid)',
    skipHeader: 'En Hojas de cálculo, no tocar la fila de encabezado al seleccionar una columna entera',
    darkSidebar: 'Barra lateral oscura',
    uiLanguageLabel: 'Idioma de la barra lateral', uiAuto: 'Automático: {language} (idioma de tu cuenta)',
    uiReload: 'Vuelve a abrir la barra lateral para verlo. El menú sigue el idioma de tu cuenta de Google.',
    saved: 'Guardado', couldNotSave: 'No se pudo guardar: {error}',
    tip: 'Consejo: los mismos estilos están en el menú Extensiones > Case Changer, así que puedes cerrar esta barra si lo prefieres.',
    rateAsk: '¿Te resulta útil? Una reseña breve en Marketplace ayuda a que otros lo encuentren.', rateYes: 'Valorar', rateNo: 'Ahora no',
    menu_cycle: 'Alternar (MAYÚS > minús > Título)', menu_repeat: 'Repetir el último estilo', menu_sidebar: 'Abrir la barra lateral', menu_help: 'Cómo funciona',
    msg_changed: 'Cambiado a {style}.', msg_nothingToChange: 'No hay nada que cambiar.', msg_nothingSelected: 'No hay nada seleccionado.',
    msg_headerSkipped: 'Se omitió la fila de encabezado.', msg_headersSkipped: 'Se omitieron {n} filas de encabezado.',
    msg_unknownStyle: 'Estilo desconocido.', msg_wrongHost: 'Abre este complemento desde Documentos, Hojas de cálculo o Presentaciones de Google.',
    msg_noLast: 'Aún no se ha usado ningún estilo. Elige uno del menú primero.',
    ask_docs: 'No hay nada seleccionado. ¿Cambiar todo el documento?',
    ask_sheets: 'No hay nada seleccionado. ¿Cambiar toda la hoja?',
    ask_slides: 'No hay nada seleccionado. ¿Cambiar toda la presentación?',
    help: 'Selecciona texto (en Hojas de cálculo: celdas; en Presentaciones: texto o un cuadro de texto) y elige un estilo en el menú Case Changer o en la barra lateral.\n\nAlternar cambia entre MAYÚSCULAS, minúsculas y Tipo Título. Repetir el último estilo hace justo eso.\nSin nada seleccionado puedes cambiar todo el archivo.\n\nEl formato, como la negrita, los enlaces y los colores, se conserva.\nNada sale de tu archivo: el complemento solo lee el texto seleccionado y lo vuelve a escribir con el nuevo estilo.'
  };

  T.fr = {
    heading: 'Mettre le texte sélectionné en',
    hint: 'Sélectionnez du texte (ou des cellules dans Sheets, ou une zone de texte dans Slides), puis cliquez sur un style. Le gras, les liens et les couleurs sont conservés.',
    cycle: 'Alterner', cycleTip: 'MAJUSCULES, puis minuscules, puis Casse De Titre',
    preview: 'Aperçu', previewTip: 'Montre le texte sélectionné dans chaque style',
    favLabel: 'Vos styles les plus utilisés', allLabel: 'Tous les styles',
    style_upper: 'MAJUSCULES', style_lower: 'minuscules', style_sentence: 'Casse de phrase', style_title: 'Casse De Titre',
    style_capitalize: 'Majuscule À Chaque Mot', style_inverse: 'cASSE iNVERSÉE', style_alternating: 'cAsSe AlTeRnÉe',
    working: 'En cours...', workingWhole: 'Traitement de tout le fichier...', reading: 'Lecture de la sélection...',
    nothingPreview: 'Rien à prévisualiser. Sélectionnez d\'abord du texte.',
    previewDone: 'Aperçu de la première ligne. Cliquez sur un style pour l\'appliquer.',
    wentWrong: 'Un problème est survenu : {error}',
    whole_docs: 'Modifier tout le document', whole_sheets: 'Modifier toute la feuille', whole_slides: 'Modifier toute la présentation',
    settings: 'Paramètres',
    keepAcronyms: 'Conserver les sigles (NASA, ONU, SNCF) en Casse de phrase et Casse De Titre',
    languageLabel: 'Langue du texte : définit les petits mots que la Casse De Titre laisse en minuscules (de, la, et, of, the...) et le I majuscule anglais',
    langAuto: 'Auto : d\'après le texte, sinon {language}',
    extraLabel: 'Garder aussi ces mots en minuscules (séparés par des espaces)', extraPlaceholder: 'ex. vs feat',
    protectedLabel: 'Ne jamais modifier ces mots (orthographe conservée dans tous les styles)', protectedPlaceholder: 'ex. iPhone eBay macOS',
    properNouns: 'La Casse de phrase met une majuscule aux pays et aux villes (France, Paris)',
    skipHeader: 'Dans Sheets, ne pas toucher à la ligne d\'en-tête quand une colonne entière est sélectionnée',
    darkSidebar: 'Barre latérale sombre',
    uiLanguageLabel: 'Langue de la barre latérale', uiAuto: 'Auto : {language} (langue de votre compte)',
    uiReload: 'Rouvrez la barre latérale pour le voir. Le menu suit la langue de votre compte Google.',
    saved: 'Enregistré', couldNotSave: 'Enregistrement impossible : {error}',
    tip: 'Astuce : les mêmes styles sont dans le menu Extensions > Case Changer, vous pouvez donc fermer cette barre.',
    rateAsk: 'Utile ? Un court avis sur le Marketplace aide d\'autres personnes à le trouver.', rateYes: 'Donner un avis', rateNo: 'Pas maintenant',
    menu_cycle: 'Alterner (MAJ > min > Titre)', menu_repeat: 'Répéter le dernier style', menu_sidebar: 'Ouvrir la barre latérale', menu_help: 'Mode d\'emploi',
    msg_changed: 'Converti en {style}.', msg_nothingToChange: 'Rien à modifier.', msg_nothingSelected: 'Rien n\'est sélectionné.',
    msg_headerSkipped: 'Ligne d\'en-tête ignorée.', msg_headersSkipped: '{n} lignes d\'en-tête ignorées.',
    msg_unknownStyle: 'Style inconnu.', msg_wrongHost: 'Ouvrez ce module complémentaire depuis Google Docs, Sheets ou Slides.',
    msg_noLast: 'Aucun style n\'a encore été utilisé. Choisissez-en un dans le menu.',
    ask_docs: 'Rien n\'est sélectionné. Modifier tout le document ?',
    ask_sheets: 'Rien n\'est sélectionné. Modifier toute la feuille ?',
    ask_slides: 'Rien n\'est sélectionné. Modifier toute la présentation ?',
    help: 'Sélectionnez du texte (dans Sheets : des cellules ; dans Slides : du texte ou une zone de texte), puis choisissez un style dans le menu Case Changer ou la barre latérale.\n\nAlterner passe de MAJUSCULES à minuscules puis à Casse De Titre. Répéter le dernier style fait ce que son nom indique.\nSans sélection, vous pouvez modifier tout le fichier.\n\nLa mise en forme (gras, liens, couleurs) est conservée.\nRien ne quitte votre fichier : le module complémentaire lit seulement le texte sélectionné et le réécrit dans le nouveau style.'
  };

  T.de = {
    heading: 'Markierten Text ändern in',
    hint: 'Text markieren (oder Zellen in Google Tabellen, oder ein Textfeld in Google Präsentationen), dann auf einen Stil klicken. Fett, Links und Farben bleiben erhalten.',
    cycle: 'Durchwechseln', cycleTip: 'GROSSBUCHSTABEN, dann kleinbuchstaben, dann Titel-Schreibweise',
    preview: 'Vorschau', previewTip: 'Zeigt den markierten Text in jedem Stil',
    favLabel: 'Am häufigsten genutzt', allLabel: 'Alle Stile',
    style_upper: 'GROSSBUCHSTABEN', style_lower: 'kleinbuchstaben', style_sentence: 'Satzanfang groß', style_title: 'Titel-Schreibweise',
    style_capitalize: 'Jedes Wort Groß', style_inverse: 'uMGEKEHRTE sCHREIBWEISE', style_alternating: 'aBwEcHsElNdE sChReIbWeIsE',
    working: 'Wird bearbeitet...', workingWhole: 'Die ganze Datei wird bearbeitet...', reading: 'Auswahl wird gelesen...',
    nothingPreview: 'Nichts für die Vorschau. Bitte zuerst Text markieren.',
    previewDone: 'Vorschau der ersten Zeile. Zum Anwenden auf einen Stil klicken.',
    wentWrong: 'Etwas ist schiefgegangen: {error}',
    whole_docs: 'Ganzes Dokument ändern', whole_sheets: 'Ganzes Tabellenblatt ändern', whole_slides: 'Ganze Präsentation ändern',
    settings: 'Einstellungen',
    keepAcronyms: 'Abkürzungen beibehalten (NASA, EU, BMW) bei Satzanfang groß und Titel-Schreibweise',
    languageLabel: 'Textsprache: legt fest, welche kleinen Wörter in der Titel-Schreibweise klein bleiben (und, der, von, of, the...) und das englische große I',
    langAuto: 'Automatisch: aus dem Text, sonst {language}',
    extraLabel: 'Auch diese Wörter klein lassen (durch Leerzeichen trennen)', extraPlaceholder: 'z. B. vs feat',
    protectedLabel: 'Diese Wörter nie ändern (Schreibweise bleibt in jedem Stil)', protectedPlaceholder: 'z. B. iPhone eBay macOS',
    properNouns: 'Satzanfang groß schreibt Länder und Städte groß (Deutschland, Berlin)',
    skipHeader: 'In Google Tabellen die Kopfzeile auslassen, wenn eine ganze Spalte markiert ist',
    darkSidebar: 'Dunkle Seitenleiste',
    uiLanguageLabel: 'Sprache der Seitenleiste', uiAuto: 'Automatisch: {language} (Sprache Ihres Kontos)',
    uiReload: 'Seitenleiste neu öffnen, um es zu sehen. Das Menü folgt der Sprache Ihres Google-Kontos.',
    saved: 'Gespeichert', couldNotSave: 'Speichern nicht möglich: {error}',
    tip: 'Tipp: Dieselben Stile stehen im Menü Erweiterungen > Case Changer, die Seitenleiste kann also geschlossen werden.',
    rateAsk: 'Nützlich? Eine kurze Bewertung im Marketplace hilft anderen, es zu finden.', rateYes: 'Bewerten', rateNo: 'Jetzt nicht',
    menu_cycle: 'Durchwechseln (GROSS > klein > Titel)', menu_repeat: 'Letzten Stil wiederholen', menu_sidebar: 'Seitenleiste öffnen', menu_help: 'So funktioniert es',
    msg_changed: 'Geändert in {style}.', msg_nothingToChange: 'Nichts zu ändern.', msg_nothingSelected: 'Nichts markiert.',
    msg_headerSkipped: 'Kopfzeile ausgelassen.', msg_headersSkipped: '{n} Kopfzeilen ausgelassen.',
    msg_unknownStyle: 'Unbekannter Stil.', msg_wrongHost: 'Dieses Add-on in Google Docs, Tabellen oder Präsentationen öffnen.',
    msg_noLast: 'Es wurde noch kein Stil verwendet. Bitte zuerst einen im Menü wählen.',
    ask_docs: 'Nichts markiert. Stattdessen das ganze Dokument ändern?',
    ask_sheets: 'Nichts markiert. Stattdessen das ganze Tabellenblatt ändern?',
    ask_slides: 'Nichts markiert. Stattdessen die ganze Präsentation ändern?',
    help: 'Text markieren (in Tabellen: Zellen; in Präsentationen: Text oder ein Textfeld), dann im Menü Case Changer oder in der Seitenleiste einen Stil wählen.\n\nDurchwechseln schaltet zwischen GROSSBUCHSTABEN, kleinbuchstaben und Titel-Schreibweise. Letzten Stil wiederholen tut genau das.\nOhne Markierung kann die ganze Datei geändert werden.\n\nFormatierungen wie Fett, Links und Farben bleiben erhalten.\nNichts verlässt Ihre Datei: Das Add-on liest nur den markierten Text und schreibt ihn im neuen Stil zurück.'
  };

  T.pt = {
    heading: 'Mudar o texto selecionado para',
    hint: 'Selecione um texto (ou células no Planilhas, ou uma caixa de texto no Slides) e clique em um estilo. Negrito, links e cores são mantidos.',
    cycle: 'Alternar', cycleTip: 'MAIÚSCULAS, depois minúsculas, depois Título',
    preview: 'Prévia', previewTip: 'Mostra como o texto selecionado ficaria em cada estilo',
    favLabel: 'Os que você mais usa', allLabel: 'Todos os estilos',
    style_upper: 'MAIÚSCULAS', style_lower: 'minúsculas', style_sentence: 'Primeira letra da frase', style_title: 'Formato De Título',
    style_capitalize: 'Maiúscula Em Cada Palavra', style_inverse: 'iNVERTER mAIÚSCULAS', style_alternating: 'aLtErNaR mAiÚsCuLaS',
    working: 'Processando...', workingWhole: 'Processando o arquivo inteiro...', reading: 'Lendo a seleção...',
    nothingPreview: 'Nada para pré-visualizar. Selecione um texto primeiro.',
    previewDone: 'Prévia da primeira linha. Clique em um estilo para aplicar.',
    wentWrong: 'Algo deu errado: {error}',
    whole_docs: 'Mudar o documento inteiro', whole_sheets: 'Mudar a planilha inteira', whole_slides: 'Mudar a apresentação inteira',
    settings: 'Configurações',
    keepAcronyms: 'Manter siglas (NASA, ONU, IBGE) em Primeira letra da frase e Formato De Título',
    languageLabel: 'Idioma do texto: define as palavras curtas que o Formato De Título mantém em minúsculas (de, da, e, of, the...) e o I maiúsculo do inglês',
    langAuto: 'Automático: pelo texto, senão {language}',
    extraLabel: 'Manter também estas palavras em minúsculas (separe com espaços)', extraPlaceholder: 'ex.: vs feat',
    protectedLabel: 'Nunca alterar estas palavras (a grafia é mantida em todos os estilos)', protectedPlaceholder: 'ex.: iPhone eBay macOS',
    properNouns: 'Primeira letra da frase põe maiúscula em países e cidades (Brasil, Lisboa)',
    skipHeader: 'No Planilhas, não mexer na linha de cabeçalho quando uma coluna inteira estiver selecionada',
    darkSidebar: 'Barra lateral escura',
    uiLanguageLabel: 'Idioma da barra lateral', uiAuto: 'Automático: {language} (idioma da sua conta)',
    uiReload: 'Reabra a barra lateral para ver. O menu segue o idioma da sua Conta do Google.',
    saved: 'Salvo', couldNotSave: 'Não foi possível salvar: {error}',
    tip: 'Dica: os mesmos estilos estão no menu Extensões > Case Changer, então você pode fechar esta barra se preferir.',
    rateAsk: 'Está sendo útil? Uma avaliação curta no Marketplace ajuda outras pessoas a encontrá-lo.', rateYes: 'Avaliar', rateNo: 'Agora não',
    menu_cycle: 'Alternar (MAIÚS > minús > Título)', menu_repeat: 'Repetir o último estilo', menu_sidebar: 'Abrir a barra lateral', menu_help: 'Como funciona',
    msg_changed: 'Alterado para {style}.', msg_nothingToChange: 'Nada para alterar.', msg_nothingSelected: 'Nada selecionado.',
    msg_headerSkipped: 'Linha de cabeçalho ignorada.', msg_headersSkipped: '{n} linhas de cabeçalho ignoradas.',
    msg_unknownStyle: 'Estilo desconhecido.', msg_wrongHost: 'Abra este complemento no Google Docs, Planilhas ou Slides.',
    msg_noLast: 'Nenhum estilo foi usado ainda. Escolha um no menu primeiro.',
    ask_docs: 'Nada selecionado. Mudar o documento inteiro?',
    ask_sheets: 'Nada selecionado. Mudar a planilha inteira?',
    ask_slides: 'Nada selecionado. Mudar a apresentação inteira?',
    help: 'Selecione um texto (no Planilhas: células; no Slides: texto ou uma caixa de texto) e escolha um estilo no menu Case Changer ou na barra lateral.\n\nAlternar passa por MAIÚSCULAS, minúsculas e Formato De Título. Repetir o último estilo faz exatamente isso.\nSem nada selecionado, você pode mudar o arquivo inteiro.\n\nA formatação, como negrito, links e cores, é mantida.\nNada sai do seu arquivo: o complemento só lê o texto selecionado e o escreve de volta no novo estilo.'
  };

  T.it = {
    heading: 'Cambia il testo selezionato in',
    hint: 'Seleziona del testo (o delle celle in Fogli, o una casella di testo in Presentazioni), poi fai clic su uno stile. Grassetto, link e colori restano.',
    cycle: 'Alterna', cycleTip: 'MAIUSCOLO, poi minuscolo, poi Stile Titolo',
    preview: 'Anteprima', previewTip: 'Mostra il testo selezionato in ogni stile',
    favLabel: 'I più usati da te', allLabel: 'Tutti gli stili',
    style_upper: 'MAIUSCOLO', style_lower: 'minuscolo', style_sentence: 'Iniziale di frase', style_title: 'Stile Titolo',
    style_capitalize: 'Iniziale Maiuscola A Ogni Parola', style_inverse: 'mAIUSCOLE iNVERTITE', style_alternating: 'mAiUsCoLe AlTeRnAtE',
    working: 'In corso...', workingWhole: 'Elaborazione dell\'intero file...', reading: 'Lettura della selezione...',
    nothingPreview: 'Niente da mostrare. Seleziona prima del testo.',
    previewDone: 'Anteprima della prima riga. Fai clic su uno stile per applicarlo.',
    wentWrong: 'Qualcosa è andato storto: {error}',
    whole_docs: 'Cambia l\'intero documento', whole_sheets: 'Cambia l\'intero foglio', whole_slides: 'Cambia l\'intera presentazione',
    settings: 'Impostazioni',
    keepAcronyms: 'Mantieni le sigle (NASA, ONU, RAI) in Iniziale di frase e Stile Titolo',
    languageLabel: 'Lingua del testo: decide le parole brevi che lo Stile Titolo lascia minuscole (di, la, e, of, the...) e la I maiuscola inglese',
    langAuto: 'Automatica: dal testo, altrimenti {language}',
    extraLabel: 'Lascia minuscole anche queste parole (separate da spazi)', extraPlaceholder: 'es. vs feat',
    protectedLabel: 'Non cambiare mai queste parole (grafia mantenuta in ogni stile)', protectedPlaceholder: 'es. iPhone eBay macOS',
    properNouns: 'Iniziale di frase mette la maiuscola a paesi e città (Italia, Roma)',
    skipHeader: 'In Fogli, lascia stare la riga di intestazione quando è selezionata un\'intera colonna',
    darkSidebar: 'Barra laterale scura',
    uiLanguageLabel: 'Lingua della barra laterale', uiAuto: 'Automatica: {language} (lingua del tuo account)',
    uiReload: 'Riapri la barra laterale per vederla. Il menu segue la lingua del tuo account Google.',
    saved: 'Salvato', couldNotSave: 'Impossibile salvare: {error}',
    tip: 'Suggerimento: gli stessi stili sono nel menu Estensioni > Case Changer, quindi puoi chiudere questa barra.',
    rateAsk: 'Ti è utile? Una breve recensione sul Marketplace aiuta altri a trovarlo.', rateYes: 'Lascia una recensione', rateNo: 'Non ora',
    menu_cycle: 'Alterna (MAIUSC > minusc > Titolo)', menu_repeat: 'Ripeti l\'ultimo stile', menu_sidebar: 'Apri la barra laterale', menu_help: 'Come funziona',
    msg_changed: 'Cambiato in {style}.', msg_nothingToChange: 'Niente da cambiare.', msg_nothingSelected: 'Nessuna selezione.',
    msg_headerSkipped: 'Riga di intestazione saltata.', msg_headersSkipped: '{n} righe di intestazione saltate.',
    msg_unknownStyle: 'Stile sconosciuto.', msg_wrongHost: 'Apri questo componente aggiuntivo da Documenti, Fogli o Presentazioni Google.',
    msg_noLast: 'Nessuno stile usato finora. Scegline prima uno dal menu.',
    ask_docs: 'Nessuna selezione. Cambiare l\'intero documento?',
    ask_sheets: 'Nessuna selezione. Cambiare l\'intero foglio?',
    ask_slides: 'Nessuna selezione. Cambiare l\'intera presentazione?',
    help: 'Seleziona del testo (in Fogli: celle; in Presentazioni: testo o una casella di testo), poi scegli uno stile dal menu Case Changer o dalla barra laterale.\n\nAlterna passa da MAIUSCOLO a minuscolo a Stile Titolo. Ripeti l\'ultimo stile fa proprio questo.\nSenza selezione puoi cambiare l\'intero file.\n\nLa formattazione, come grassetto, link e colori, resta.\nNiente esce dal tuo file: il componente legge solo il testo selezionato e lo riscrive nel nuovo stile.'
  };

  T.nl = {
    heading: 'Geselecteerde tekst wijzigen in',
    hint: 'Selecteer tekst (of cellen in Spreadsheets, of een tekstvak in Presentaties) en klik op een stijl. Vet, links en kleuren blijven behouden.',
    cycle: 'Wisselen', cycleTip: 'HOOFDLETTERS, dan kleine letters, dan Titelstijl',
    preview: 'Voorbeeld', previewTip: 'Toont de geselecteerde tekst in elke stijl',
    favLabel: 'Meest door jou gebruikt', allLabel: 'Alle stijlen',
    style_upper: 'HOOFDLETTERS', style_lower: 'kleine letters', style_sentence: 'Zin met hoofdletter', style_title: 'Titelstijl',
    style_capitalize: 'Elk Woord Met Een Hoofdletter', style_inverse: 'oMGEKEERDE lETTERS', style_alternating: 'aFwIsSeLeNdE lEtTeRs',
    working: 'Bezig...', workingWhole: 'Het hele bestand wordt verwerkt...', reading: 'Selectie wordt gelezen...',
    nothingPreview: 'Niets om te tonen. Selecteer eerst tekst.',
    previewDone: 'Voorbeeld van de eerste regel. Klik op een stijl om die toe te passen.',
    wentWrong: 'Er ging iets mis: {error}',
    whole_docs: 'Het hele document wijzigen', whole_sheets: 'Het hele blad wijzigen', whole_slides: 'De hele presentatie wijzigen',
    settings: 'Instellingen',
    keepAcronyms: 'Afkortingen behouden (NASA, EU, NS) in Zin met hoofdletter en Titelstijl',
    languageLabel: 'Taal van de tekst: bepaalt welke kleine woorden in Titelstijl klein blijven (de, het, van, of, the...) en de Engelse hoofdletter I',
    langAuto: 'Automatisch: uit de tekst, anders {language}',
    extraLabel: 'Houd ook deze woorden klein (gescheiden door spaties)', extraPlaceholder: 'bijv. vs feat',
    protectedLabel: 'Deze woorden nooit wijzigen (schrijfwijze blijft in elke stijl)', protectedPlaceholder: 'bijv. iPhone eBay macOS',
    properNouns: 'Zin met hoofdletter geeft landen en steden een hoofdletter (Nederland, Amsterdam)',
    skipHeader: 'Laat in Spreadsheets de koprij met rust als een hele kolom is geselecteerd',
    darkSidebar: 'Donkere zijbalk',
    uiLanguageLabel: 'Taal van de zijbalk', uiAuto: 'Automatisch: {language} (taal van je account)',
    uiReload: 'Open de zijbalk opnieuw om het te zien. Het menu volgt de taal van je Google-account.',
    saved: 'Opgeslagen', couldNotSave: 'Opslaan mislukt: {error}',
    tip: 'Tip: dezelfde stijlen staan in het menu Uitbreidingen > Case Changer, dus je kunt deze zijbalk sluiten.',
    rateAsk: 'Handig? Een korte review in de Marketplace helpt anderen het te vinden.', rateYes: 'Beoordelen', rateNo: 'Niet nu',
    menu_cycle: 'Wisselen (HOOFD > klein > Titel)', menu_repeat: 'Laatste stijl herhalen', menu_sidebar: 'Zijbalk openen', menu_help: 'Zo werkt het',
    msg_changed: 'Gewijzigd in {style}.', msg_nothingToChange: 'Niets te wijzigen.', msg_nothingSelected: 'Niets geselecteerd.',
    msg_headerSkipped: 'Koprij overgeslagen.', msg_headersSkipped: '{n} koprijen overgeslagen.',
    msg_unknownStyle: 'Onbekende stijl.', msg_wrongHost: 'Open deze add-on vanuit Google Documenten, Spreadsheets of Presentaties.',
    msg_noLast: 'Er is nog geen stijl gebruikt. Kies er eerst een in het menu.',
    ask_docs: 'Niets geselecteerd. Het hele document wijzigen?',
    ask_sheets: 'Niets geselecteerd. Het hele blad wijzigen?',
    ask_slides: 'Niets geselecteerd. De hele presentatie wijzigen?',
    help: 'Selecteer tekst (in Spreadsheets: cellen; in Presentaties: tekst of een tekstvak) en kies een stijl in het menu Case Changer of in de zijbalk.\n\nWisselen schakelt tussen HOOFDLETTERS, kleine letters en Titelstijl. Laatste stijl herhalen doet precies dat.\nZonder selectie kun je het hele bestand wijzigen.\n\nOpmaak zoals vet, links en kleuren blijft behouden.\nNiets verlaat je bestand: de add-on leest alleen de geselecteerde tekst en schrijft die terug in de nieuwe stijl.'
  };

  T.tl = {
    heading: 'Baguhin ang napiling teksto sa',
    hint: 'I-highlight ang teksto (o pumili ng mga cell sa Sheets, o text box sa Slides), pagkatapos ay i-click ang isang estilo. Nananatili ang bold, mga link at mga kulay.',
    cycle: 'Ikot ng titik', cycleTip: 'MALALAKING TITIK, tapos maliliit na titik, tapos Titik Pamagat',
    preview: 'Preview', previewTip: 'Ipakita ang napiling teksto sa bawat estilo',
    favLabel: 'Pinakaginagamit mo', allLabel: 'Lahat ng estilo',
    style_upper: 'MALALAKING TITIK', style_lower: 'maliliit na titik', style_sentence: 'Titik ng pangungusap', style_title: 'Titik Pamagat',
    style_capitalize: 'Malaking Titik Sa Bawat Salita', style_inverse: 'bALIKTAD nA tITIK', style_alternating: 'sAlItAn Na TiTiK',
    working: 'Pinoproseso...', workingWhole: 'Pinoproseso ang buong file...', reading: 'Binabasa ang napili...',
    nothingPreview: 'Walang mai-preview. Pumili ng teksto muna.',
    previewDone: 'Preview ng unang linya. I-click ang isang estilo para ilapat.',
    wentWrong: 'May problema: {error}',
    whole_docs: 'Baguhin ang buong dokumento', whole_sheets: 'Baguhin ang buong sheet', whole_slides: 'Baguhin ang buong presentasyon',
    settings: 'Mga Setting',
    keepAcronyms: 'Panatilihin ang mga akronim (NASA, DOH, LRT) sa Titik ng pangungusap at Titik Pamagat',
    languageLabel: 'Wika ng teksto: itinatakda ang maiikling salitang nananatiling maliit sa Titik Pamagat (ng, sa, at, of, the...) at ang malaking I ng Ingles',
    langAuto: 'Auto: mula sa teksto, kung hindi ay {language}',
    extraLabel: 'Panatilihing maliit din ang mga salitang ito (paghiwalayin ng espasyo)', extraPlaceholder: 'hal. vs feat',
    protectedLabel: 'Huwag baguhin ang mga salitang ito (nananatili ang baybay sa bawat estilo)', protectedPlaceholder: 'hal. iPhone eBay macOS',
    properNouns: 'Ang Titik ng pangungusap ay naglalagay ng malaking titik sa mga araw, buwan at lugar (Lunes, Maynila)',
    skipHeader: 'Sa Sheets, huwag galawin ang header row kapag napili ang buong column',
    darkSidebar: 'Dark na sidebar',
    uiLanguageLabel: 'Wika ng sidebar', uiAuto: 'Auto: {language} (wika ng iyong account)',
    uiReload: 'Buksan muli ang sidebar para makita. Ang menu ay sumusunod sa wika ng iyong Google account.',
    saved: 'Na-save', couldNotSave: 'Hindi ma-save: {error}',
    tip: 'Tip: ang mga estilong ito ay nasa menu na Extensions > Case Changer, kaya maaari mong isara ang sidebar na ito.',
    rateAsk: 'Nakakatulong ba? Ang maikling review sa Marketplace ay tumutulong sa iba na mahanap ito.', rateYes: 'Mag-review', rateNo: 'Hindi ngayon',
    menu_cycle: 'Ikot ng titik (MALAKI > maliit > Pamagat)', menu_repeat: 'Ulitin ang huling estilo', menu_sidebar: 'Buksan ang sidebar', menu_help: 'Paano gamitin',
    msg_changed: 'Binago sa {style}.', msg_nothingToChange: 'Walang binago.', msg_nothingSelected: 'Walang napili.',
    msg_headerSkipped: 'Nilaktawan ang header row.', msg_headersSkipped: 'Nilaktawan ang {n} header row.',
    msg_unknownStyle: 'Hindi kilalang estilo.', msg_wrongHost: 'Buksan ang add-on na ito mula sa Google Docs, Sheets o Slides.',
    msg_noLast: 'Wala pang estilong nagamit. Pumili muna ng isa sa menu.',
    ask_docs: 'Walang napili. Baguhin ang buong dokumento?',
    ask_sheets: 'Walang napili. Baguhin ang buong sheet?',
    ask_slides: 'Walang napili. Baguhin ang buong presentasyon?',
    help: 'Pumili ng teksto (sa Sheets: mga cell; sa Slides: teksto o text box), pagkatapos ay pumili ng estilo sa menu ng Case Changer o sa sidebar.\n\nAng Ikot ng titik ay lumilipat sa MALALAKING TITIK, maliliit na titik at Titik Pamagat. Ang Ulitin ang huling estilo ay inuulit ang huling ginamit.\nKung walang napili, maaari mong baguhin ang buong file.\n\nNananatili ang format gaya ng bold, mga link at mga kulay.\nWalang umaalis sa iyong file: binabasa ng add-on ang napiling teksto at isinusulat itong muli sa bagong estilo.'
  };

  T.tr = {
    heading: 'Seçili metni şuna dönüştür',
    hint: 'Bir metni seçin (E-Tablolar\'da hücreleri, Slaytlar\'da bir metin kutusunu) ve bir stile tıklayın. Kalın yazı, bağlantılar ve renkler korunur.',
    cycle: 'Sırayla değiştir', cycleTip: 'BÜYÜK HARF, sonra küçük harf, sonra Başlık Düzeni',
    preview: 'Önizleme', previewTip: 'Seçili metnin her stilde nasıl görüneceğini gösterir',
    favLabel: 'En çok kullandıklarınız', allLabel: 'Tüm stiller',
    style_upper: 'BÜYÜK HARF', style_lower: 'küçük harf', style_sentence: 'Cümle düzeni', style_title: 'Başlık Düzeni',
    style_capitalize: 'Her Sözcüğün İlk Harfi Büyük', style_inverse: 'tERS bÜYÜK kÜÇÜK', style_alternating: 'sIrAyLa BüYüK kÜçÜk',
    working: 'İşleniyor...', workingWhole: 'Tüm dosya işleniyor...', reading: 'Seçim okunuyor...',
    nothingPreview: 'Önizlenecek bir şey yok. Önce metin seçin.',
    previewDone: 'İlk satırın önizlemesi. Uygulamak için bir stile tıklayın.',
    wentWrong: 'Bir sorun oluştu: {error}',
    whole_docs: 'Tüm belgeyi değiştir', whole_sheets: 'Tüm sayfayı değiştir', whole_slides: 'Tüm sunuyu değiştir',
    settings: 'Ayarlar',
    keepAcronyms: 'Kısaltmaları koru (NASA, TBMM, AB) Cümle düzeni ve Başlık Düzeni içinde',
    languageLabel: 'Metin dili: Başlık Düzeni\'nde küçük kalan kısa sözcükleri (ve, ile, için, of, the...) ve İngilizce büyük I harfini belirler',
    langAuto: 'Otomatik: metinden, olmazsa {language}',
    extraLabel: 'Bu sözcükleri de küçük bırak (boşlukla ayırın)', extraPlaceholder: 'örn. vs feat',
    protectedLabel: 'Bu sözcükleri asla değiştirme (yazım her stilde korunur)', protectedPlaceholder: 'örn. iPhone eBay macOS',
    properNouns: 'Cümle düzeni ülke ve şehir adlarını büyük harfle başlatır (Türkiye, İstanbul)',
    skipHeader: 'E-Tablolar\'da tüm sütun seçildiğinde başlık satırına dokunma',
    darkSidebar: 'Koyu kenar çubuğu',
    uiLanguageLabel: 'Kenar çubuğu dili', uiAuto: 'Otomatik: {language} (hesap diliniz)',
    uiReload: 'Görmek için kenar çubuğunu yeniden açın. Menü, Google hesabınızın dilini izler.',
    saved: 'Kaydedildi', couldNotSave: 'Kaydedilemedi: {error}',
    tip: 'İpucu: aynı stiller Uzantılar > Case Changer menüsünde de var, bu yüzden kenar çubuğunu kapatabilirsiniz.',
    rateAsk: 'İşinize yaradı mı? Marketplace\'te kısa bir değerlendirme başkalarının bulmasına yardımcı olur.', rateYes: 'Değerlendir', rateNo: 'Şimdi değil',
    menu_cycle: 'Sırayla değiştir (BÜYÜK > küçük > Başlık)', menu_repeat: 'Son stili yinele', menu_sidebar: 'Kenar çubuğunu aç', menu_help: 'Nasıl kullanılır',
    msg_changed: '{style} olarak değiştirildi.', msg_nothingToChange: 'Değiştirilecek bir şey yok.', msg_nothingSelected: 'Hiçbir şey seçilmedi.',
    msg_headerSkipped: 'Başlık satırı atlandı.', msg_headersSkipped: '{n} başlık satırı atlandı.',
    msg_unknownStyle: 'Bilinmeyen stil.', msg_wrongHost: 'Bu eklentiyi Google Dokümanlar, E-Tablolar veya Slaytlar içinden açın.',
    msg_noLast: 'Henüz bir stil kullanılmadı. Önce menüden birini seçin.',
    ask_docs: 'Hiçbir şey seçilmedi. Tüm belge değiştirilsin mi?',
    ask_sheets: 'Hiçbir şey seçilmedi. Tüm sayfa değiştirilsin mi?',
    ask_slides: 'Hiçbir şey seçilmedi. Tüm sunu değiştirilsin mi?',
    help: 'Bir metin seçin (E-Tablolar\'da hücreler; Slaytlar\'da metin veya bir metin kutusu), sonra Case Changer menüsünden ya da kenar çubuğundan bir stil seçin.\n\nSırayla değiştir; BÜYÜK HARF, küçük harf ve Başlık Düzeni arasında geçer. Son stili yinele, son kullanılan stili uygular.\nHiçbir şey seçili değilse tüm dosyayı değiştirebilirsiniz.\n\nKalın yazı, bağlantılar ve renkler gibi biçimlendirme korunur.\nDosyanızdan hiçbir şey çıkmaz: eklenti yalnızca seçtiğiniz metni okur ve yeni stilde geri yazar.'
  };

  T.el = {
    heading: 'Αλλαγή του επιλεγμένου κειμένου σε',
    hint: 'Επιλέξτε κείμενο (ή κελιά στα Υπολογιστικά φύλλα, ή ένα πλαίσιο κειμένου στις Παρουσιάσεις) και κάντε κλικ σε ένα στυλ. Η έντονη γραφή, οι σύνδεσμοι και τα χρώματα διατηρούνται.',
    cycle: 'Εναλλαγή', cycleTip: 'ΚΕΦΑΛΑΙΑ, μετά πεζά, μετά Μορφή Τίτλου',
    preview: 'Προεπισκόπηση', previewTip: 'Δείχνει το επιλεγμένο κείμενο σε κάθε στυλ',
    favLabel: 'Τα πιο συχνά σας', allLabel: 'Όλα τα στυλ',
    style_upper: 'ΚΕΦΑΛΑΙΑ', style_lower: 'πεζά', style_sentence: 'Μορφή πρότασης', style_title: 'Μορφή Τίτλου',
    style_capitalize: 'Κεφαλαίο Σε Κάθε Λέξη', style_inverse: 'αΝΤΙΣΤΡΟΦΗ πΕΖΩΝ', style_alternating: 'εΝαΛλΑσΣόΜεΝα',
    working: 'Γίνεται επεξεργασία...', workingWhole: 'Επεξεργασία ολόκληρου του αρχείου...', reading: 'Ανάγνωση της επιλογής...',
    nothingPreview: 'Δεν υπάρχει κάτι για προεπισκόπηση. Επιλέξτε πρώτα κείμενο.',
    previewDone: 'Προεπισκόπηση της πρώτης γραμμής. Κάντε κλικ σε ένα στυλ για εφαρμογή.',
    wentWrong: 'Κάτι πήγε στραβά: {error}',
    whole_docs: 'Αλλαγή όλου του εγγράφου', whole_sheets: 'Αλλαγή όλου του φύλλου', whole_slides: 'Αλλαγή όλης της παρουσίασης',
    settings: 'Ρυθμίσεις',
    keepAcronyms: 'Διατήρηση ακρωνυμίων (NASA, ΕΕ, ΟΗΕ) σε Μορφή πρότασης και Μορφή Τίτλου',
    languageLabel: 'Γλώσσα κειμένου: ορίζει τις μικρές λέξεις που μένουν πεζές στη Μορφή Τίτλου (και, του, της, of, the...) και το αγγλικό κεφαλαίο I',
    langAuto: 'Αυτόματα: από το κείμενο, αλλιώς {language}',
    extraLabel: 'Κρατήστε πεζές και αυτές τις λέξεις (χωρισμένες με κενά)', extraPlaceholder: 'π.χ. vs feat',
    protectedLabel: 'Να μην αλλάζουν ποτέ αυτές οι λέξεις (η γραφή διατηρείται σε κάθε στυλ)', protectedPlaceholder: 'π.χ. iPhone eBay macOS',
    properNouns: 'Η Μορφή πρότασης βάζει κεφαλαίο σε ημέρες, μήνες και τόπους (Δευτέρα, Αθήνα)',
    skipHeader: 'Στα Υπολογιστικά φύλλα, να μένει ανέγγιχτη η γραμμή κεφαλίδας όταν επιλέγεται ολόκληρη στήλη',
    darkSidebar: 'Σκούρα πλαϊνή γραμμή',
    uiLanguageLabel: 'Γλώσσα πλαϊνής γραμμής', uiAuto: 'Αυτόματα: {language} (γλώσσα του λογαριασμού σας)',
    uiReload: 'Ανοίξτε ξανά την πλαϊνή γραμμή για να το δείτε. Το μενού ακολουθεί τη γλώσσα του λογαριασμού σας Google.',
    saved: 'Αποθηκεύτηκε', couldNotSave: 'Δεν αποθηκεύτηκε: {error}',
    tip: 'Συμβουλή: τα ίδια στυλ υπάρχουν στο μενού Επεκτάσεις > Case Changer, άρα μπορείτε να κλείσετε αυτή τη γραμμή.',
    rateAsk: 'Σας φαίνεται χρήσιμο; Μια σύντομη κριτική στο Marketplace βοηθά άλλους να το βρουν.', rateYes: 'Αξιολόγηση', rateNo: 'Όχι τώρα',
    menu_cycle: 'Εναλλαγή (ΚΕΦΑΛΑΙΑ > πεζά > Τίτλος)', menu_repeat: 'Επανάληψη τελευταίου στυλ', menu_sidebar: 'Άνοιγμα πλαϊνής γραμμής', menu_help: 'Πώς λειτουργεί',
    msg_changed: 'Άλλαξε σε {style}.', msg_nothingToChange: 'Δεν υπάρχει κάτι για αλλαγή.', msg_nothingSelected: 'Δεν έχει επιλεγεί τίποτα.',
    msg_headerSkipped: 'Η γραμμή κεφαλίδας παραλείφθηκε.', msg_headersSkipped: 'Παραλείφθηκαν {n} γραμμές κεφαλίδας.',
    msg_unknownStyle: 'Άγνωστο στυλ.', msg_wrongHost: 'Ανοίξτε αυτό το πρόσθετο από τα Έγγραφα, τα Υπολογιστικά φύλλα ή τις Παρουσιάσεις Google.',
    msg_noLast: 'Δεν έχει χρησιμοποιηθεί ακόμη κάποιο στυλ. Επιλέξτε πρώτα ένα από το μενού.',
    ask_docs: 'Δεν έχει επιλεγεί τίποτα. Να αλλάξει όλο το έγγραφο;',
    ask_sheets: 'Δεν έχει επιλεγεί τίποτα. Να αλλάξει όλο το φύλλο;',
    ask_slides: 'Δεν έχει επιλεγεί τίποτα. Να αλλάξει όλη η παρουσίαση;',
    help: 'Επιλέξτε κείμενο (στα Υπολογιστικά φύλλα: κελιά· στις Παρουσιάσεις: κείμενο ή ένα πλαίσιο κειμένου) και διαλέξτε ένα στυλ από το μενού Case Changer ή την πλαϊνή γραμμή.\n\nΗ Εναλλαγή περνά από ΚΕΦΑΛΑΙΑ σε πεζά και σε Μορφή Τίτλου. Η Επανάληψη τελευταίου στυλ κάνει ακριβώς αυτό.\nΧωρίς επιλογή μπορείτε να αλλάξετε ολόκληρο το αρχείο.\n\nΗ μορφοποίηση, όπως έντονα, σύνδεσμοι και χρώματα, διατηρείται.\nΤίποτα δεν φεύγει από το αρχείο σας: το πρόσθετο διαβάζει μόνο το επιλεγμένο κείμενο και το γράφει ξανά στο νέο στυλ.'
  };

  var NAMES = { en: 'English', ms: 'Bahasa Malaysia', id: 'Bahasa Indonesia', es: 'Español', fr: 'Français', de: 'Deutsch',
                pt: 'Português', it: 'Italiano', nl: 'Nederlands', tl: 'Tagalog', tr: 'Türkçe', el: 'Ελληνικά' };

  function has(lang) { return T.hasOwnProperty(lang); }

  /** All strings for a language, with English filling any gap. */
  function get(lang) {
    var out = {}, k;
    for (k in T.en) if (T.en.hasOwnProperty(k)) out[k] = T.en[k];
    if (has(lang) && lang !== 'en') for (k in T[lang]) if (T[lang].hasOwnProperty(k)) out[k] = T[lang][k];
    return out;
  }

  function format(text, vars) {
    return String(text).replace(/\{(\w+)\}/g, function (m, key) { return vars && vars.hasOwnProperty(key) ? vars[key] : m; });
  }

  return { get: get, has: has, format: format, NAMES: NAMES, LANGS: Object.keys(T), KEYS: Object.keys(T.en) };
})();
